ALTER TYPE "WalletOwnerType" ADD VALUE IF NOT EXISTS 'MOBILE_MONEY';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'MOBILE_MONEY_CREDIT';
ALTER TYPE "WalletTransactionType" ADD VALUE IF NOT EXISTS 'MOBILE_MONEY_WITHDRAWAL';
