/**
 * Twilio Content template -> Meta `message_templates` creation payload.
 *
 * Pure, so the translation can be tested against captured fixtures without a
 * network call. The scripts do the I/O.
 */
import {
  WHATSAPP_TEMPLATES,
  getButtonUrlVar,
  templateCloudName,
  templateLanguage,
  type WhatsAppTemplateName,
} from '../../src/common/constants/whatsapp-templates';
import { urlAction, variablesIn, type SourceTemplate } from './twilio-source';

/**
 * The name to create the template under in Meta.
 *
 * Taken from Twilio's `friendly_name`, NOT the registry's `cloud.name`. Those
 * defaults were derived from the template key before anything could be checked
 * against a live account, and all 27 turned out wrong — the real names are
 * versioned (`rabotka_otp_auth`, `rabotka_kyc_pending_menu_v3`) and not
 * derivable. One name across both providers also means a template can be found
 * in either console by searching the same string.
 */
function metaName(source: SourceTemplate): string {
  return source.content.friendly_name;
}

export interface MetaComponent {
  type: 'HEADER' | 'BODY' | 'FOOTER' | 'BUTTONS';
  format?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'DOCUMENT';
  text?: string;
  /** AUTHENTICATION only: Meta appends its own "do not share" line. */
  add_security_recommendation?: boolean;
  /** AUTHENTICATION only, on the FOOTER: renders "expires in N minutes". */
  code_expiration_minutes?: number;
  example?: {
    header_text?: string[];
    body_text?: string[][];
    header_handle?: string[];
  };
  buttons?: MetaButton[];
}

export interface MetaButton {
  type: 'URL' | 'QUICK_REPLY' | 'OTP' | 'FLOW';
  text?: string;
  url?: string;
  example?: string[];
  otp_type?: 'COPY_CODE';
  autofill_text?: string;
  /**
   * FLOW only. The flow binds at creation — a send carries just the token —
   * which is why this can never come out of `translate()`: Twilio Content has
   * no Flow action to translate from. See `definitions.ts`.
   */
  flow_id?: string;
  navigate_screen?: string;
  flow_action?: 'navigate' | 'data_exchange';
}

export interface MetaTemplatePayload {
  name: string;
  language: string;
  category: 'UTILITY' | 'AUTHENTICATION' | 'MARKETING';
  components: MetaComponent[];
}

export interface TranslationIssue {
  key: WhatsAppTemplateName;
  problem: string;
}

export interface Translation {
  key: WhatsAppTemplateName;
  payload: MetaTemplatePayload;
  /** What the registry currently believes the name is, for the drift report. */
  registryName: string;
  issues: TranslationIssue[];
}

/**
 * Renumber a URL's variable to `{{1}}`.
 *
 * Twilio shares ONE `{{n}}` namespace across body and button — a template whose
 * body uses 1..8 puts the button variable at `{{9}}`. Meta gives the button its
 * own namespace where the variable is always `{{1}}`. Body text needs no
 * renumbering because body variables are contiguous from 1 in every template
 * here; only the button moves.
 */
function renumberButtonUrl(url: string): string {
  return url.replace(/\{\{\d+\}\}/g, '{{1}}');
}

/**
 * An example value for every body variable, in order.
 *
 * Meta requires examples at creation time and rejects a template without them.
 * Twilio's own `variables` map already holds realistic samples, so they are
 * reused rather than invented — a placeholder like "text" reads as low effort
 * to a human reviewer and invites rejection.
 */
function bodyExamples(
  source: SourceTemplate,
  bodyVars: string[],
): string[] | null {
  if (bodyVars.length === 0) return null;
  return bodyVars.map((v) => source.content.variables?.[v] ?? `exemple ${v}`);
}

function textOf(source: SourceTemplate): string {
  // A WhatsApp card renders media + title + button, never a body — so Twilio
  // cards carry the copy in `title` and leave `body` null. Meta has no such
  // quirk and requires a BODY, which is where that text belongs.
  const { body, title } = source.spec;
  return (body ?? title ?? '').trim();
}

export function translate(
  source: SourceTemplate,
  opts: { mediaHandle?: string } = {},
): Translation {
  const { key } = source;
  const issues: TranslationIssue[] = [];
  const registry = WHATSAPP_TEMPLATES[key];
  const components: MetaComponent[] = [];

  const category = registry.category;
  const action = urlAction(source.spec);
  const buttonVar = getButtonUrlVar(key);

  // ── AUTHENTICATION ───────────────────────────────────────────────────────
  // Meta owns this shape entirely: the body copy is generated by Meta from the
  // locale, and the only choices are the security recommendation, the code
  // expiry, and the copy-code button. Sending our own body text is rejected.
  if (category === 'AUTHENTICATION') {
    // No body text of our own: Meta generates the copy from the locale and
    // rejects a custom body. The only inputs are the security recommendation,
    // the expiry footer and the copy-code button label — all of which Twilio's
    // whatsapp/authentication type already carries.
    const expiry = source.spec.code_expiration_minutes;
    const auth: MetaComponent[] = [
      {
        type: 'BODY',
        add_security_recommendation:
          source.spec.add_security_recommendation ?? false,
      },
    ];
    if (expiry) {
      auth.push({ type: 'FOOTER', code_expiration_minutes: expiry });
    }
    auth.push({
      type: 'BUTTONS',
      buttons: [
        {
          type: 'OTP',
          otp_type: 'COPY_CODE',
          text:
            source.spec.actions?.find((a) => a.type === 'COPY_CODE')
              ?.copy_code_text ?? 'Copier le code',
        },
      ],
    });
    return {
      key,
      payload: {
        name: metaName(source),
        language: templateLanguage(key),
        category,
        components: auth,
      },
      registryName: templateCloudName(key),
      issues,
    };
  }

  // ── HEADER (cards only) ──────────────────────────────────────────────────
  if (source.spec.media?.length) {
    if (!opts.mediaHandle) {
      issues.push({
        key,
        problem:
          'card needs an IMAGE header, but no media handle was supplied — run upload-media.ts first',
      });
    }
    components.push({
      type: 'HEADER',
      format: 'IMAGE',
      example: { header_handle: [opts.mediaHandle ?? 'MISSING_MEDIA_HANDLE'] },
    });
  }

  // ── BODY ─────────────────────────────────────────────────────────────────
  const text = textOf(source);
  if (!text) {
    issues.push({
      key,
      problem: 'no body or title text found in the Twilio template',
    });
  }
  const bodyVars = variablesIn(text);
  const examples = bodyExamples(source, bodyVars);
  components.push({
    type: 'BODY',
    text,
    ...(examples ? { example: { body_text: [examples] } } : {}),
  });

  // ── BUTTONS ──────────────────────────────────────────────────────────────
  if (action?.url) {
    const urlVars = variablesIn(action.url);
    if (urlVars.length > 1) {
      issues.push({
        key,
        problem: `button URL uses ${urlVars.length} variables; Meta allows exactly one`,
      });
    }
    if (urlVars.length === 1 && urlVars[0] !== buttonVar) {
      // The check that would have caught the viewWorkerPortfolio bug.
      issues.push({
        key,
        problem:
          `Twilio button URL uses {{${urlVars[0]}}} but the registry declares ` +
          `buttonUrlVar/urlSuffixVar = ${buttonVar ?? 'none'} — the send would put ` +
          `that value in the body instead of the button`,
      });
    }
    const example = urlVars.length
      ? (source.content.variables?.[urlVars[0]] ?? 'exemple')
      : undefined;
    components.push({
      type: 'BUTTONS',
      buttons: [
        {
          type: 'URL',
          text: action.title ?? 'Ouvrir',
          url: renumberButtonUrl(action.url),
          ...(example
            ? {
                example: [
                  renumberButtonUrl(action.url).replace('{{1}}', example),
                ],
              }
            : {}),
        },
      ],
    });
  } else if (buttonVar) {
    issues.push({
      key,
      problem: `registry declares a button variable (${buttonVar}) but the Twilio template has no URL action`,
    });
  }

  return {
    key,
    payload: {
      name: metaName(source),
      language: templateLanguage(key),
      category,
      components,
    },
    registryName: templateCloudName(key),
    issues,
  };
}
